### ISSUE TITLE
Pathological input: Unclosed inline links

### ISSUE THREAD

**Issue by mity** [commonmark/cmark#214]
The following command generates Markdown input which takes inadequately long time with current Cmark's master head (88c8ad1). (On my Windows machine it  takes 13.076 seconds.)

```
$ python -c 'print("[a](b" * 50000)'
```

Seems to be regression, Cmark 0.27.1 processes it fine (0.063 s)

**Comment by mity** [comment]
The commit a9da6782761e4d3ac7dfd3193fa43b73824afef4 is responsible for the regression.

**Comment by jgm** [comment]
Anything that fixes this should also add this case to the pathological tests in the test suite.
