### ISSUE TITLE
Document that running the output of cmark through an HTML parser can itself allow for denial of service

### ISSUE THREAD

**Issue by DemiMarie** [commonmark/cmark#223]
I have not been able to find a single HTML parser that cannot be coerced into a hang by maliciously crafted HTML.

As such, while CMark is designed to safely be used on untrusted data, any HTML sanitizer that uses the HTML5 parsing algorithm is likely vulnerable.  Instead, an lossier sanitizer must be used, or one that cannot hang found.

Obviously this is not cmark’s fault – Markdown allows for raw HTML and so an HTML sanitizer is usually necessary.  However, it *should* be mentioned in the documentation.

**Comment by mity** [comment]
Should man page of `ls` say that doing `ls | broken_program` may be bad idea and lead to bad results, including hang, crash or unexpected output?

**Comment by DemiMarie** [comment]
No.  In this case, however, *every* such program is broken, and it appears
that very few people are aware of this.

**Comment by jgm** [comment]
@DemiMarie can you provide some examples of HTML inputs that hang the parsers?  I'd like to try on the HTML parsers I use.

While I agree that it's not cmark's responsibility to document flaws in other software, I think it would not hurt to add a couple sentences about parser performance and the risk of DOS attacks to the "Security" section in README.md.  If we did, we could also mention the risk of similar problems in HTML sanitization software, though any such mention should be backed up by a link to a page documenting the problem in common HTML sanitizers.

**Comment by DemiMarie** [comment]
@jgm The following perl expressions each generate a string that hangs every HTML parser I have come across, with the exception of [my patched version of html5ever](https://github.com/servo/html5ever/pulls/297).

```perl
use strict;
use warnings;
my $q = 50000; # time is quadratic in $q
my $hang1 = '<i>' x $q . '<a>' x $q . '</a>' x $q;
my $hang2 = '<i>' x $q . '<div>' x $q;
```
