### ISSUE TITLE
"cmark --smart" incorrectly converts straight quote to "&lsquo;" rather than "&rsquo;"

### ISSUE THREAD

**Issue by giucal** [commonmark/cmark#227]
Given the test source

    Test of [cmark]'s `--smart` option. There's something wrong.
    
    [cmark]: http://commonmark.org

`cmark --smart` produces

    <p>Test of <a href="http://commonmark.org">cmark</a>‘s <code>--smart</code> option. There’s something wrong.</p>

whereas the correct output would be

    <p>Test of <a href="http://commonmark.org">cmark</a>’s <code>--smart</code> option. There’s something wrong.</p>

The problem is that the first straight quote (in `[cmark]'s`) is erroneously converted into an opening single quote (`&lsquo;`) instead of an apostrophe (`&rsquo;`).

As far as I can tell, this happens whenever

- a `'x` follows a non-alphanumeric character (as in `]'x`, `"'x`, or `*'x`) and
- there is a subsequent straight quote at the right boundary of a word (as in `x'x` or `x'`).

**Comment by jgm** [comment]
Thanks for the report!
