### ISSUE TITLE
Link reference definition inside of Setext headings

### ISSUE THREAD

**Issue by shyouhei** [commonmark/cmark#231]
I guess it's rather intentional for the definition of setext headings to avoid mentioning link reference definitions.

http://spec.commonmark.org/0.28/#setext-heading

> A setext heading consists of one or more lines of text, each containing at least one non-whitespace character, with no more than 3 spaces indentation, followed by a setext heading underline. The lines of text must be such that, were they not followed by the setext heading underline, they would be interpreted as a paragraph: they cannot be interpretable as a code fence, ATX heading, block quote, thematic break, list item, or HTML block.

So it's up to each implementation whether they allow link reference definitions inside of setext headings or not.  Fair enough.

Having said that however, current cmark behaviour is strange.  For instance consider this input

```markdown
[bar]: bar
[foo][bar]
==========
```

As far as I read the spec this is either "a link reference definition, followed by a setext heading" or "a setext heading, including a link reference definition".  Cmark, on the other hand, offers us a third interpretation; this is _not_ a link reference definition.

```
% cmark <<'EOS'
[bar]: bar
[foo][bar]
==========
EOS
<h1>[bar]: bar
[foo][bar]</h1>
```

Is this an intended behaviour?

**Comment by mity** [comment]
Can likely be closed. Since specs 0.29, this generates

```
<h1><a href="bar">foo</a></h1>
```
