### ISSUE TITLE
cmark doesn't seem to encode < and > in headers.

### ISSUE THREAD

**Issue by ademko** [commonmark/cmark#234]
cmark (tested with current git version) doesn't seem to encode < and > in headers. For example, this:

    Glib::RefPtr<T>
    --------------

Converts:

    <h2>Glib::RefPtr<T></h2>

(ideally the <T> should be &lt;T&gt; etc)

**Comment by jgm** [comment]
Here `<T>` is being parsed as raw HTML.  See the CommonMark
spec to see why this is according to spec.  (We don't limit
to known HTML tags.)

Since this is code, it is recommended that you put the
whole thing inside single backticks.  If you don't want
to do that, you can backslash-escape the `<`.

**Comment by ademko** [comment]
Wow, that's unexpected, but it seems to be there in part 6.8 "raw html" of the spec. Also, github's preview confirms this to :)

Thanks, and thanks for the great software.
