### ISSUE TITLE
Bold link in italics followed by a period

### ISSUE THREAD

**Issue by regseb** [commonmark/cmark#237]
Hello,

A bold link in italics followed by a period prints a roman regular link wrapped by `***`. ([live demo](http://spec.commonmark.org/dingus/?text=***%5Bfoo%5D(http%3A%2F%2Fbar.baz%2F)***.))

`***[foo](http://bar.baz/)***.` : ***[foo](http://bar.baz/)***.
`***[foo](http://bar.baz/)***` : ***[foo](http://bar.baz/)***
`**[foo](http://bar.baz/)**.` : **[foo](http://bar.baz/)**.
`*[foo](http://bar.baz/)*.` : *[foo](http://bar.baz/)*.
`***foo***.` : ***foo***.

**Comment by jgm** [comment]
Thanks, this does look like a bug to me.  As you note,
`*()*.` produces italics, and `**()**.` bold; we only get
the problem with `***()***.`.

**Comment by regseb** [comment]
The rendering is good in GitHub and with the [live demo](https://spec.commonmark.org/dingus/?text=***%5Bfoo%5D(http%3A%2F%2Fbar.baz%2F)***.). 🎉

[image](https://user-images.githubusercontent.com/1262990/80416473-7b390480-88d4-11ea-93cc-d71706f63f3d.png)
