### ISSUE TITLE
Consider changing the default from unsafe to safe

### ISSUE THREAD

**Issue by Flowdalic** [commonmark/cmark#239]
I suggest changing the [default modus operandi of cmark from unsafe](https://github.com/commonmark/cmark#security) to safe. I fear otherwise people will run cmake with the defaults to produce HTML which they deliver to their user, allowing an attacker to inject dangerous stuff into that HTML. Given the popularity of CommonMark, I do wonder if we don't have already a certain amount of vulnerable sites because of cmark's default behavior.

Or am I missing something? What is the reasoning behind performing unsafe operations per default, versus having to explicitly enable them?

**Comment by jgm** [comment]
The `--safe` mode is not the default because passing through
raw HTML is standard, traditional Markdown behavior.

+++ Florian Schmaus [Oct 17 17 00:29 ]:
