### ISSUE TITLE
Nytt märke

### ISSUE THREAD

**Issue by Zari65** [commonmark/cmark#242]
https://github.com/commonmark/cmark/blob/5da792fc3714f66a88aabb5d13cb0eed674cb6c5/src/cmark.h#L633

**Comment by Zari65** [comment]
linguist/lib/linguist/languages.yml

**Comment by Zari65** [comment]
linguist/lib/linguist/languages.yml

**Comment by jgm** [comment]
Sorry, I don't understand this issue.
Can you explain?

**Comment by kivikakk** [comment]
Looks like spam/bot; I'll mark it as such.

**Comment by fingolfin** [comment]
Perhaps close (or even delete?) this issue then?
