### ISSUE TITLE
GitHub repo doesn't run Appveyor tests anymore

### ISSUE THREAD

**Issue by nwellnhof** [commonmark/cmark#251]
When committing or sending PRs, the Appveyor tests aren't anymore. This apparently stopped working about four months ago: https://ci.appveyor.com/project/jgm/cmark

**Comment by jgm** [comment]
I added commonmark/cmark to appveyor (previously it was only doing jgm/cmark).  I suspect this is the problem.

**Comment by nwellnhof** [comment]
https://ci.appveyor.com/project/commonmark/cmark still produces an error message: "Project not found or access denied."

**Comment by nwellnhof** [comment]
The following link works: https://ci.appveyor.com/project/jgm/cmark-0ub06

**Comment by franklinyu** [comment]
I think the link still doesn't work. Currently it points to <https://ci.appveyor.com/project/commonmark/cmark> but that page shows "Project not found or access denied."
