### ISSUE TITLE
man: paragraphs in list items not indented

### ISSUE THREAD

**Issue by wangp** [commonmark/cmark#258]
The man writer doesn't indent/nest paragraphs within a list item, e.g.
~~~~markdown
 1. item one

 2. item two

    item two paragraph 2.

    item two paragraph 3.
~~~~
generates:
~~~~man
.IP "1." 4
item one
.IP "2." 4
item two
.PP
item two paragraph 2.
.PP
item two paragraph 3.
~~~~
which renders as:
~~~~
       1.  item one

       2.  item two

       item two paragraph 2.

       item two paragraph 3.
~~~~

**Comment by nwellnhof** [comment]
I think the man renderer also doesn't handle nested lists and blockquotes at all. FWIW, here's some code that I wrote a while ago that properly handles nested indentation:

https://github.com/apache/lucy-clownfish/blob/master/compiler/src/CFCCMan.c#L416

I don't remember the details, but it's trickier than I initially thought.
