### ISSUE TITLE
Add encoding metadata

### ISSUE THREAD

**Issue by contrapunctus-1** [commonmark/cmark#260]
Currently, using cmark v0.26.1-1+b1 (Debian Stable) to export to HTML results in Unicode characters being rendered as garbage strings (on Firefox v61). This was fixed by adding `<meta charset="UTF-8">` to the HTML file. Assuming this isn't a browser-specific issue, perhaps cmark should add this in the HTML output?

**Comment by nwellnhof** [comment]
cmark doesn't produce whole HTML documents, so it wouldn't make much sense to output a *meta* element which must appear in the *head* of an HTML document.

**Comment by jgm** [comment]
I agree with @nwellnhof. You'd normally want to insert the output cmark produces into the body element of an HTML template. See for example [lcmark](https://github.com/jgm/lcmark) for one tool that makes that possible.
