### ISSUE TITLE
Final newline when rendering

### ISSUE THREAD

**Issue by joneshf** [commonmark/cmark#261]
I'm working on some markdown stuff, and found whenever I render something, it ends up with a trailing newline. After some tracing, it seems to be coming from this section in `cmark_render`
https://github.com/commonmark/cmark/blob/53ef343a65e3da19d605cfb7e8909004cfac954e/src/render.c#L173-L176

I noticed there's a comment `ensure final newline`, but not much more than that. I assume it's here for a good reason, but couldn't find anything in the CommonMark spec. What's the reason? What happens if there's no trailing newline? If it's pivotal to parsing/rendering properly, can it be added to the spec?

**Comment by jgm** [comment]
It's a unix convention that text files must end with a
newline character.

This doesn't have anything to do with parsing (hence
not mentioned in the spec). It's purely a rendering
issue.

**Comment by joneshf** [comment]
Awesome! Thanks for the quick response. Is there a way to render without assuming it will be saved to a text file? It's fine if not, wanting to make sure I'm not missing a different way to solve the problem.

Given some `cmark_node` `foo`, let's say I render `foo` and then parse that rendered text. Should I expect to get back `foo`? Will the final newline (if not already there) change the markdown?

**Comment by jgm** [comment]
The final newline shouldn't make a difference to the meaning of the document.

If you want to render without a final newline, I'd recommend just piping the output through something that removes it.  e.g. `cmark file.md | perl -pi -e 'chomp if eof'`.
