### ISSUE TITLE
Encoding of HTML character entity

### ISSUE THREAD

**Issue by justasandiegoguy2018** [commonmark/cmark#262]
Not sure how best to describe....
But if the markdown contains  "1 \&\#8260;2" which is 1/2
the cmark changes to hex(E2 81 84 3C]
then in Safari then appears as 1â„2

NOTE : there are NO spaces in the example .... I had to put them in other wise this page converted them

**Comment by jgm** [comment]
This is the UTF-8 encoding of &#8260;. So, not a bug.

Safari will display it correctly if you tell it that
the page is UTF-8 encoded.  You can do that by
including

      <meta charset="UTF-8">

in the `<head>` section of the HTML page.  Or
on the menu, View -> Text Encoding -> UTF-8.

**Comment by justasandiegoguy2018** [comment]
Thank you for your response..... I did find that by putting the UTF-8 meta
tag into the header that it worked... However due to the many "extensions"
that I required for my project, I have opted to write my own markdown
parser...... and honestly... it was no where near as difficult as I
thought.... Mine currently supports Tables, TOC, Footnotes as well as all
the "standard" features.   Thanks again
