### ISSUE TITLE
xml back to markdown

### ISSUE THREAD

**Issue by jeroen** [commonmark/cmark#264]
I was wondering if anyone has worked on a tool to convert the xml AST back to markdown? We would like to structurally edit markdown documents, preferably using xml tools (xpath, etc).

**Comment by nwellnhof** [comment]
I could probably whip up an XSLT stylesheet in half an hour.

**Comment by jeroen** [comment]
I think that would be fantastic.

**Comment by nwellnhof** [comment]
Here's a first attempt: https://gist.github.com/nwellnhof/1594ec597ae06836bc2f974641ec4df7

Note that a MD->XML->MD roundtrip will lose a bit of information.

@jgm If you like, I can commit the XSLT stylesheet to the `tools` directory.

**Comment by jeroen** [comment]
Thanks @nwellnhof ! This works quite well. Can you explain why verbatim html is not supported?

Also: I see your name appear in libxslt as well so I might as ask here: in my libxslt bindings the `<xsl:message>` triggers a hard error via `xsltSetGenericErrorFunc`. Is there any way I can distinguish between a terminating and non terminating message in my `xmlGenericErrorFunc` callback?

**Comment by nwellnhof** [comment]
@jeroen The stylesheet in the pull request also handles HTML blocks and inlines.

libxslt will invoke the error handler for every `<xsl:message>` regardless of the `terminate` attribute. But unless `terminate` is set to `yes`, it will continue to process the stylesheet. There's no structured error facility like in libxml2.
