### ISSUE TITLE
Timeline for cutting a new release

### ISSUE THREAD

**Issue by iwasrobbed** [commonmark/cmark#270]
Hi @jgm 👋 

I really appreciate all your continued work on this 👍👍 

Do you have a time in mind for when you'll be cutting a new release from `master`? The last one was Oct 2017

<img width="672" alt="screen shot 2018-09-21 at 9 22 26 am" src="https://user-images.githubusercontent.com/317671/45883722-e11bec80-bd7f-11e8-811b-7999f41fb469.png">

I'm using an older version in [Down](https://github.com/iwasrobbed/Down) and I just want to make sure it's versioned to the latest code when I update it.

**Comment by jgm** [comment]
I don't have a specific time line for a new release.
Unless there are security bug fixes for cmark, I'll
probably wait til commonmark 0.29 and there are still
quite a few issues that need to be resolved for that:

https://github.com/commonmark/CommonMark/milestones

**Comment by iwasrobbed** [comment]
Perfect, thanks John!
