### ISSUE TITLE
Getting image alt-text

### ISSUE THREAD

**Issue by Gofake1** [commonmark/cmark#279]
I couldn't find a `cmark_node_get_alt`- equivalent function for image nodes, which would explain why the HTML renderer seems to access the data structure directly.

Would it be possible to include this functionality in the API?

**Comment by nwellnhof** [comment]
AFAICS, image "alt" text is simply the contents (children) of the image node.

**Comment by Gofake1** [comment]
You're right, thanks for pointing that out.
