### ISSUE TITLE
Skipping heading ranks

### ISSUE THREAD

**Issue by cup** [commonmark/cmark#283]
With Asciidoc, it is recommended to keep headings in order. That is to say, H4
should not follow H2, better for H3 to follow H2. If you break this it gives a
warning:

~~~
asciidoctor: WARNING: readme.adoc: line 11: section title out of sequence:
expected level 2, got level 3
~~~

i was somewhat surprised by this, but then i noticed this is an official
recommendation as well:

- https://developer.mozilla.org/Web/HTML/Element/Heading_Elements#Usage_notes
- https://w3.org/WAI/tutorials/page-structure/headings

Markdown has no restriction on header order and in fact doesnt even advise
against out of order headings:

https://spec.commonmark.org/0.28#atx-headings

**Comment by cup** [comment]
https://github.com/wallyqs/org-ruby/issues/65

**Comment by cup** [comment]
https://github.com/commonmark/cmark/issues/283
https://github.com/ruby/rdoc/issues/700
https://github.com/wallyqs/org-ruby/issues/65

**Comment by cup** [comment]
https://github.com/commonmark/cmark/issues/283
https://github.com/jgarber/redcloth/issues/56
https://github.com/ruby/rdoc/issues/700
https://github.com/wallyqs/org-ruby/issues/65

**Comment by jgm** [comment]
If the suggestion is to add a note to the spec, then this should go in commonmark/CommonMark, not here (this is for the C implementation).  Personally, though, I'm not sure this belongs in the spec.  The spec defines a mapping from commonmark -> an abstract syntax tree (not HTML). Markdown has never forbidden skips in header levels, so we don't either.
