### ISSUE TITLE
Missing #include in parser.h

### ISSUE THREAD

**Issue by phoney** [commonmark/cmark#287]
The Down project uses the code from the cmark project (currently it uses the code pulled from the v0.28.3 tag). A crashing bug was reported to Down that I've tracked down to a missing #include in parser.h. https://github.com/iwasrobbed/Down/issues/126
The stack trace for the crash shows:

```
0 xcalloc
1 cmark_chunk_free
2 reference_free
```
cmark_chunk_free() doesn't call xcalloc. It calls mem->free(). Because of the missing #include the compiler calls mem-> xcalloc() instead of mem->free(). Making the #includes in parser.h like this fixes the crash:

```#include <stdio.h>
#include "references.h"
#include "node.h"
#include "buffer.h"
#include "memory.h"
```

Using the struct keyword on this line in parser.h contributes to this issue
`  struct cmark_reference_map *refmap;`

Reordering the #includes in references.c also fixes this if references.h comes before parser.h. I'm not sure why references.h has to go first in parser.h to fix this though.

I don't know if there's something about how cmark is compiled in the Down project that causes this or if the reference_free() function isn't called with most markdown or if there's some other reason this hasn't been noticed before.

Hope you can fix this.

**Comment by iwasrobbed** [comment]
Thanks @phoney ! I'm happy to accept pull requests but prefer they be made upstream in https://github.com/commonmark/cmark

**Comment by jgm** [comment]
Not sure why it hasn't come up before -- it does seem that this include is necessary!
