### ISSUE TITLE
Leftover includes of "memory.h" cause build errors on iOS

### ISSUE THREAD

**Issue by vzsg** [commonmark/cmark#290]
Hi!

In the past, there was a header file in the library called "memory.h", which FWIW has been merged into the cmark.h header.

Yet, a few source files are still trying to include it:
- [buffer.c](https://github.com/commonmark/cmark/blob/f90f2567a0ef0bfed119c19d9281c8c5d68d78c3/src/buffer.c#L13)
- [chunk.h](https://github.com/commonmark/cmark/blob/f90f2567a0ef0bfed119c19d9281c8c5d68d78c3/src/chunk.h#L9)
- [iterator.h](https://github.com/commonmark/cmark/blob/f90f2567a0ef0bfed119c19d9281c8c5d68d78c3/src/iterator.h#L9)
- [parser.h](https://github.com/commonmark/cmark/blob/f90f2567a0ef0bfed119c19d9281c8c5d68d78c3/src/parser.h#L8)
- [references.h](https://github.com/commonmark/cmark/blob/f90f2567a0ef0bfed119c19d9281c8c5d68d78c3/src/references.h#L4)
- [render.h](https://github.com/commonmark/cmark/blob/f90f2567a0ef0bfed119c19d9281c8c5d68d78c3/src/render.h#L11)

In some obscure scenarios, like when [trying to use cmark on iOS in the same project as another library that includes a file called memory.h](https://github.com/iwasrobbed/Down/pull/125), the compiler gets confused and hell breaks loose.

Is it possible to remove these offending includes?

TIA.

**Comment by jgm** [comment]
Thanks for noticing!
