### ISSUE TITLE
Wrong parse result: backslash in mathml

### ISSUE THREAD

**Issue by lp-contentplus** [commonmark/cmark#293]
Input:

    <math><msup><mi>a</mi><mrow><mo>-</mo><mi>n</mi></mrow></msup><mo>=</mo><msup><mfenced><mfrac><mn>1</mn><mi>a</mi></mfrac></mfenced><mi>n</mi></msup><mo>,</mo><mo>&#xA0;</mo><mi>a</mi><mo>&#xA0;</mo><mo>&#x2208;</mo><mi>R</mi><mo>\</mo><mo>&#xA0;</mo><mfenced open="{" close="}"><mn>0</mn></mfenced><mo>,</mo><mo>&#xA0;</mo><mi>n</mi><mo>&#xA0;</mo><mo>&#x2208;</mo><mi>R</mi><mo>\</mo><mo>&#xA0;</mo><mfenced open="{" close="}"><mn>0</mn></mfenced></math>

Output:

    <p><math><msup><mi>a</mi><mrow><mo>-</mo><mi>n</mi></mrow></msup><mo>=</mo><msup><mfenced><mfrac><mn>1</mn><mi>a</mi></mfrac></mfenced><mi>n</mi></msup><mo>,</mo><mo> </mo><mi>a</mi><mo> </mo><mo>∈</mo><mi>R</mi><mo>&lt;/mo&gt;<mo> </mo><mfenced open="{" close="}"><mn>0</mn></mfenced><mo>,</mo><mo> </mo><mi>n</mi><mo> </mo><mo>∈</mo><mi>R</mi><mo>&lt;/mo&gt;<mo> </mo><mfenced open="{" close="}"><mn>0</mn></mfenced></math></p>

Code breaks at `<mo>\</mo>...`. Output turns into: `&lt;/mo&gt;...`

Expected output:

Input wrapped in `<p>`

**Comment by jgm** [comment]
This is correct according to the spec.  `<mo>` gets parsed as an HTML tag, but the `\` occurs outside the tag and hence functions as a backslash-escape for the following character, `<`.

I understand why this is non-ideal; you'd like to be able to copy-paste the mathml.  But this won't work when the parts of the mathml between tags contain symbols with an independent meaning in commonmark (`\`, `*`, `_`, `[`, etc.).

One option would be to simply insert
```
<p><math><msup><mi>a</mi><mrow><mo>-</mo><mi>n</mi></mrow></msup><mo>=</mo><msup><mfenced><mfrac><mn>1</mn><mi>a</mi></mfrac></mfenced><mi>n</mi></msup><mo>,</mo><mo> </mo><mi>a</mi><mo> </mo><mo>∈</mo><mi>R</mi><mo>\</mo><mo> </mo><mfenced open="{" close="}"><mn>0</mn></mfenced><mo>,</mo><mo> </mo><mi>n</mi><mo> </mo><mo>∈</mo><mi>R</mi><mo>&lt;/mo&gt;<mo> </mo><mfenced open="{" close="}"><mn>0</mn></mfenced></math></p>
```
as a raw HTML block (including the p tags, with blank space above and below).  Then cmark will (again, according to the spec) parse the whole thing as verbatim HTML.

**Comment by lp-contentplus** [comment]
Ok, I didn't know that. Is there any way to make it parse some inline content as raw HTML? (by wrapping it in something)

    *aaa** <something><math></math></something> rest *here*

**Comment by jgm** [comment]
Another approach would be to replace the backslash with `&#92;`.

**Comment by lp-contentplus** [comment]
Eh... Thank you ;)

**Comment by jgm** [comment]
> Is there any way to make it parse some inline content as raw HTML? (by wrapping it in something)

pandoc's markdown has the `raw_attribute` extension which allows this:
```
this is `<mo>raw HTML</mo>`{=html}.
```
But it's not part of commonmark at this point.
