### ISSUE TITLE
Can't install pod on macOS 10.15 Catalina

### ISSUE THREAD

**Issue by aaronraimist** [commonmark/cmark#302]
```
% pod install
Analyzing dependencies
Downloading dependencies
Installing cmark (0.24.1)
[!] /bin/bash -c 
set -e
echo `pwd`
sed -i '' 's/include <\(cmark.*\)>/include "\1"/' src/cmark.h
mkdir -p build; cd build && cmake -G Xcode ..

/Users/tt/Library/Caches/CocoaPods/Pods/Release/cmark/0.24.1-ec027
CMake Error:
  Xcode 1.5 not supported.


CMake Error: Could not create named generator Xcode

Generators
* Unix Makefiles               = Generates standard UNIX makefiles.
  Ninja                        = Generates build.ninja files.
  Xcode                        = Generate Xcode project files.
  CodeBlocks - Ninja           = Generates CodeBlocks project files.
  CodeBlocks - Unix Makefiles  = Generates CodeBlocks project files.
  CodeLite - Ninja             = Generates CodeLite project files.
  CodeLite - Unix Makefiles    = Generates CodeLite project files.
  Sublime Text 2 - Ninja       = Generates Sublime Text 2 project files.
  Sublime Text 2 - Unix Makefiles
                               = Generates Sublime Text 2 project files.
  Kate - Ninja                 = Generates Kate project files.
  Kate - Unix Makefiles        = Generates Kate project files.
  Eclipse CDT4 - Ninja         = Generates Eclipse CDT 4.0 project files.
  Eclipse CDT4 - Unix Makefiles= Generates Eclipse CDT 4.0 project files.
```

**Comment by jgm** [comment]
We don't maintain anything cocoapod related.  Why don't you report this to whoever manages the cocoapod for pandoc?  (Note that the reported version, 0.24, is quite old, so in any case they need to update the sources.)

**Comment by jgm** [comment]
Or, if you can reproduce the problem using the current cmark code with our standard build procedure, feel free to open an issue here.

**Comment by aaronraimist** [comment]
Alright thanks. Just so you know the CocoaPods page links to this repo. https://cocoapods.org/pods/cmark

![Screen Shot 2019-06-04 at 6 02 44 PM](https://user-images.githubusercontent.com/5855073/58919238-f6a92a80-86f2-11e9-902b-c6d6d94692f5.png)

**Comment by jgm** [comment]
I don't know anything about cocoapods, but it looks as if there's something called a "podspec" which gives build instructions.  My suggestion would be to contact the maintainer Chris Eidhof (listed on the page you reference above) with the problem you're having (and also note that the cmark version packaged in quite out of date).

**Comment by chriseidhof** [comment]
The Pod is old, I'll figure out how I can get it deleted from CocoaPods. Sorry about that.

**Comment by yo2bh** [comment]
@chriseidhof - Still facing same issue on Catalina mac OS.
Any update on this ?
