### ISSUE TITLE
Multi-paragraph list item nested in blockquote

### ISSUE THREAD

**Issue by mity** [commonmark/cmark#304]
Input:
```
>* foo
>
>  bar
```

Expected output:
```
<blockquote>
<ul>
<li>
<p>foo</p>
<p>bar</p>
</li>
</ul>
</blockquote>
```

Actual output:
```
<blockquote>
<ul>
<li>foo</li>
</ul>
<p>bar</p>
</blockquote>
```

Rationale:
See https://spec.commonmark.org/0.29/#example-226. If I prepend every line of it with blockquote mark, it should be the same output, just wrapped in the blockquote, as per https://spec.commonmark.org/0.29/#block-quotes, the "basic case".

(Originally reported at https://github.com/raphlinus/pulldown-cmark/issues/358)

**Comment by jgm** [comment]
Is this the same issue as https://github.com/commonmark/commonmark-spec/issues/460 ?

**Comment by mity** [comment]
Probably yes, at least the input in [this comment](https://github.com/commonmark/commonmark-spec/issues/460#issuecomment-293702833) seems to be.

**Comment by jgm** [comment]
I think the underlying problem has to do with whether a following space is included in the block quote start marker. Currently a following space is always gobbled, and that can lead to violations of the Principle of Uniformity when (a) the quoted content contains significant indentation, and (b) a space is not uniformly added after `>`.

**Comment by jgm** [comment]
And yes, I believe it is a spec bug.  Spec says:

>  If a string of lines Ls constitute a sequence of blocks Bs, then the result of prepending a block quote marker to the beginning of each line in Ls is a block quote containing Bs.

A block quote marker

> consists of 0-3 spaces of initial indent, plus (a) the character > together with a following space, or (b) a single character > not followed by a space.

So in your example the block quote marker on line 1 is just `>`, while the block quote markers on the following lines are `>`+SPACE.  If we strip these off, then, we get
```
* foo

 bar
```
which is a list followed by a paragraph.  Thus the implementations are giving you just what the spec says.

**Comment by mity** [comment]
I see. I missed the `>` + space makes the sign here. 

Indeed, if I change the input into

```
>* foo
>
>  bar
```

it then works as expected in all the noted implementations.

Sorry for the noise.
