### ISSUE TITLE
CMake cannot find cmark

### ISSUE THREAD

**Issue by encombhat** [commonmark/cmark#307]
find_package(cmark) is not working even though cmark is installed correctly and cmark claims to have CMake's find_package() support.

Log:
```
CMake Error at CMakeLists.txt:89 (find_package):
  By not providing "Findcmark.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "cmark", but
  CMake did not find one.

  Could not find a package configuration file provided by "cmark" with any of
  the following names:

    cmarkConfig.cmake
    cmark-config.cmake

  Add the installation prefix of "cmark" to CMAKE_PREFIX_PATH or set
  "cmark_DIR" to a directory containing one of the above files.  If "cmark"
  provides a separate development package or SDK, be sure it has been
  installed.
```

Apparantly cmark installs its .cmake file in $libdir/cmake/cmark.cmake, but CMake expects cmarkConfig.cmake.

**Comment by jgm** [comment]
I am not sure what part of the build is creating this file...nothing I can see in CMakeLists.txt or src/CMakeLists.txt seems to refer to it.  As far as I can see, we aren't overriding any defaults.
If you want to make a suggestion as to how to change our CMakeLists.txt, I'm all ears.

**Comment by nwellnhof** [comment]
> cmark claims to have CMake's find_package() support.

Where did you find this claim?

**Comment by encombhat** [comment]
Ok I'll try creating a PR.

**Comment by compnerd** [comment]
#320 should enable the use of `find_package` at least for the build tree case, I think that there is a little bit of work left to enable the use of it in the install tree.  That work will amount largely to renaming the export file and installing the cmarkConfig.cmake.
