### ISSUE TITLE
Deprecated?

### ISSUE THREAD

**Issue by tsfischer** [commonmark/cmark#308]
Cocoapods claims CMark is deprecated, but I can't find any mention of that here.

What's the current status of this library?

**Comment by jgm** [comment]
Not deprecated.  I don't know what cocoapods is, but it sounds like some kind of distribution mechanism for macos.  Perhaps what they mean is that the cocoapods package is deprecated. In any case, this library is still very much alive.

**Comment by chriseidhof** [comment]
Cocoapoads is a package manager for iOS/Mac

I deprecated the pod specification, as I can't do a good job at maintaining it.
