### ISSUE TITLE
Inline nodes can reference text data of parent block

### ISSUE THREAD

**Issue by nwellnhof** [commonmark/cmark#309]
When parsing inline nodes, some pieces of text are kept in the parent block's content buffer and referenced from inline children as non-allocated `cmark_chunk` pointing directly into the parent's buffer. If the parent is freed, these pointers become invalid. This can lead to memory corruption. for example when moving inline nodes to another tree and deleting the old parent.

I'd suggest to copy all text data to inline children (i. e. use `chunk_clone` instead of `chunk_dup`). Then we could also think about removing the content field for block nodes.

**Comment by jgm** [comment]
Sounds good.  Do you want to submit a PR?

**Comment by jgm** [comment]
I wonder what performance impact this would have on normal use.  (More allocations.)

**Comment by nwellnhof** [comment]
Here's a branch exploring the idea: https://github.com/nwellnhof/cmark/commits/rework-node-struct

The additional allocations cause about 10-15% overhead on my machine. Some other improvements bring this down to 5-10%. Note that the slowdown should only be visible with the built-in renderers. Parsing and iterating all literals using the public API should be faster than before.

I really like some of the simplifications in the branch. But if we want to avoid the slowdown, another approach is to clone literals when an inline node is unlinked.

**Comment by jgm** [comment]
Simpler is good.  I'm for it, even if there's a small slowdown.

**Comment by jgm** [comment]
Can you submit your branch as a PR?

**Comment by jgm** [comment]
Here's what I measured in benchmarks (`make bench`):

before this change: 1.33 mean
after: 1.54 mean

That's about 18% -- were you getting different measurements for the performance impact?

**Comment by jgm** [comment]
Even with the impact, I think the change is a good idea, but it's more than I'd hoped.

**Comment by nwellnhof** [comment]
I get 1.21 before and 1.29 after.

**Comment by nwellnhof** [comment]
Under MinGW: 2.22 before, 2.31 after

**Comment by nwellnhof** [comment]
On my MacBook, the results of each run vary a lot. But the slowdown doesn't seem higher than 10%.

**Comment by jgm** [comment]
Strange.  My results are pretty consistent with what I reported on my old macbook pro.
On linux I see 0.169 old, 0.180 new, 6%.  That's reassuring.
