### ISSUE TITLE
<script> tags contained by other HTML tags are incorrectly parsed for markdown

### ISSUE THREAD

**Issue by parkermalenke** [commonmark/cmark#310]
[According to the spec](https://spec.commonmark.org/0.29/#example-140) script tags should be treated as a complete HTML block and their contents should not be parsed for markdown.

If you wrap a script tag in another HTML tag, however, the script tag contents *is* parsed for markdown.

```html
<div>
<script type="text/javascript">
// JavaScript example

document.getElementById("demo").innerHTML = "Hello JavaScript!";
</script>
</div>
okay
```
[See in dingus](https://spec.commonmark.org/dingus/?text=%3Cdiv%3E%0A%3Cscript%20type%3D%22text%2Fjavascript%22%3E%0A%2F%2F%20JavaScript%20example%0A%0Adocument.getElementById(%22demo%22).innerHTML%20%3D%20%22Hello%20JavaScript!%22%3B%0A%3C%2Fscript%3E%0A%3C%2Fdiv%3E%0Aokay)

Outputs:

```html

<div>
<script type="text/javascript">
// JavaScript example
<p>document.getElementById(&quot;demo&quot;).innerHTML = &quot;Hello JavaScript!&quot;;
</script></p>
</div>
okay
```

**Comment by jgm** [comment]
This accords with the spec, actually.  You have a type 6 start condition.  The end condition for this is a blank line.  So the HTML block extends down to the blank line.  To avoid this, leave a blank line before the opening script tag.

**Comment by parkermalenke** [comment]
@jgm ah, thanks for clarifying. That was indeed the issue. A blank line before the script tag solved the problem.
