### ISSUE TITLE
Inline code is rendered with extra or missing spaces at beginning or end

### ISSUE THREAD

**Issue by egrimley** [commonmark/cmark#316]
If the inline code starts or ends with a space then strange things happen when rendering as CommonMark:

```
$ printf '` `' | cmark -t commonmark
`   `
$ printf '`  `' | cmark -t commonmark
`    `
$ printf '` x`' | cmark -t commonmark
`  x `
$ printf '`x `' | cmark -t commonmark
` x  `
$ printf '` x `' | cmark -t commonmark
`x`
```

If the inline code contains just spaces, then repeated parsing and rerendering makes the string get longer and longer.

HTML output is also a bit strange:

```
$ printf '` x `' | cmark -t html
<p><code>x</code></p>
$ printf '`  x `' | cmark -t html
<p><code> x</code></p>
```

**Comment by jgm** [comment]
There have been some changes to the spec around treatment of spaces at the beginning and end of inline code since the commonmark renderer was written; it needs some updating.

**Comment by jgm** [comment]
To understand the HTML output, see the spec.
"If the resulting string both begins and ends with a space character, but does not consist entirely of space characters, a single space character is removed from the front and back. This allows you to include code that begins or ends with backtick characters, which must be separated by whitespace from the opening or closing backtick strings."
