### ISSUE TITLE
Export a Free method to release returned markup text

### ISSUE THREAD

**Issue by darianmiller** [commonmark/cmark#330]
When attempting to use a statically linked DLL, there should be a proper way of releasing the memory allocated for the returned markup text.

This could be as simple as a new export in cmark.h
CMARK_EXPORT
void freemarkup(void *ptr);

And in cmark.c:
void freemarkup(void *ptr) { free(ptr); }

Otherwise the calling parent process needs to release memory created by a child DLL, likely using different memory managers.  In my case, calling the DLL from a Delphi application.

**Comment by darianmiller** [comment]
I started looking into the cmark-gfm project and it has an export which would work to satisfy this request:

CMARK_GFM_EXPORT
cmark_mem *cmark_get_default_mem_allocator();

**Comment by jgm** [comment]
@nwellnhof - what do you think, should we export something like this too?

**Comment by nwellnhof** [comment]
To be more precise, this issue arises on Windows if you link the cmark DLL to the CRT (C library) statically. It should already be possible to work around this issue by using a custom memory allocator. Exposing the default allocator is a good idea nevertheless.
