### ISSUE TITLE
<p> instead <H1> in first line (utf-8-BOM)

### ISSUE THREAD

**Issue by andreikorzhyts** [commonmark/cmark#334]
If header 1 level (**# Heade**r) in first line,
I get **\<p\> # Header\</p\>** instead **\<H1\>Header\</H1\>**.

**Comment by jgm** [comment]
Can't reproduce.
Are you sure you have a space between `#` and `H`?

**Comment by andreikorzhyts** [comment]
Yes, I do all right, according to specification.
I compared different files and found (it seems to me) the cause of the issue. This is UTF-8-BOM.
What is your opinion on whether utf-8-BOM should be supported?

**Comment by jgm** [comment]
Ah yes -- we should presumably skip a BOM marker at the beginning of input.  That would be a worth while change.

**Comment by andreikorzhyts** [comment]
I'm glad you find this useful. When can we expect this improvement?
