### ISSUE TITLE
no terget for uninstall in Makefile

### ISSUE THREAD

**Issue by vired** [commonmark/cmark#336]
add `uninstall` terget in Makefile.

it only has `install` but doesn't have `uninstall`.

so what should we do to uninstall .

**Comment by jgm** [comment]
The `install` target just calls the `install` target in the Makefile generated by cmake.  This Makefile doesn't have an `uninstall` target.

I'm afraid it's pretty much standard practice in the \*nix world to have `install` targets without `uninstall`. Generally if you want to be able to uninstall things you need to use a package manager.  If you're on Debian/Ubuntu, `checkinstall` can be helpful.

**Comment by jgm** [comment]
See https://stackoverflow.com/questions/41471620/cmake-support-make-uninstall
As noted there, when you do `make install`, a file `install_manifest.txt` will be created in the `build` directory listing all the files installed.
```
xargs rm < build/install_manifest.txt
```
will remove them all.

I just added an `uninstall` target that does this.

**Comment by waldyrious** [comment]
> I just added an uninstall target that does this.

Just for convenience and future reference, that was done in ef20bfbd5.

**Comment by vired** [comment]
thank you
