### ISSUE TITLE
q: about readme 

### ISSUE THREAD

**Issue by mobop** [commonmark/cmark#337]
in readme 
```
Output in HTML, groff man, LaTeX, CommonMark, and a custom XML format is supported.

```
what does it mean by out put to CommonMark?

**Comment by jgm** [comment]
```
source --parser--> abstract syntax tree --renderer--> commonmark
```
one of the renderers produces commonmark.  So, you can convert commonmark to commonmark (which will tidy and normalize the formatting), or create an abstract syntax tree programmatically and render commonmark.
