### ISSUE TITLE
Support namespaces in tag names

### ISSUE THREAD

**Issue by ioquatix** [commonmark/cmark#341]
It can be useful to embed tags with namespaces and have them pass through correctly.

Some parsers already support this:

```
irb(main):002:0> Kramdown::Document.new("<foo:bar>\nbaz\n</foo:bar>").to_html
=> "<foo:bar>\nbaz\n</foo:bar>\n"
```

Tag names and attribute names should be allowed to contain `:`.

Further discussion:

- https://github.com/gjtorikian/commonmarker/pull/123
- https://github.com/mity/md4c/issues/112

**Comment by ioquatix** [comment]
Other parsers don't support it:

```
irb(main):005:0> CommonMarker.render_doc("<foo:bar>\nbaz\n</foo:bar>").to_html
=> "<p><a href=\"foo:bar\">foo:bar</a>\nbaz\n&lt;/foo:bar&gt;</p>\n"
```

**Comment by movermeyer** [comment]
I would like to voice opposition to anything that makes this gem deviate from the Commonmark spec in any way. We're relying on this gem to be a faithful implementation of the spec, with a nice Ruby interface.

It should accept no more, and no less than what the spec says.

**Comment by movermeyer** [comment]
> Some parsers already support this

It doesn't matter what Kramdown does, since it is a Markdown renderer, not a Commonmark renderer.

**Comment by ioquatix** [comment]
The point is to show that it's feasible/possible and that some implementations do it already. It's useful to have a point of reference when considering how we evolve the spec (or not).

**Comment by movermeyer** [comment]
I am soooo sorry. I'm in the wrong repo...


Sorry, sorry, sorry...

**Comment by ioquatix** [comment]
@movermeyer is there a better place to make issues regarding changes to the spec?

**Comment by jgm** [comment]
This is for cmark, the C implementation of the spec.
To raise issues regarding changes to the spec, you should start at talk.commonmark.org.  There is also a repo commonmark/commonmark-spec, but it is better to discuss on the forum first.

**Comment by ioquatix** [comment]
@jgm I made [a topic for discussion](https://talk.commonmark.org/t/allow-namespace-in-tag-names-and-attributes/3465) and added a PR to the spec here: https://github.com/commonmark/commonmark-spec/pull/648
