### ISSUE TITLE
Indentation of ordered lists (and maybe others)

### ISSUE THREAD

**Issue by ioquatix** [commonmark/cmark#343]
Is there any difference between:

```
1. Foo
2. Bar
```

and

```
1.  Foo
2.  Bar
```

I've been playing around with normalising markdown and I noticed that my ordered lists (and maybe others) are being rewritten with two leading spaces instead of one. Just wondering if we can add an option to control this or if there is some other reason why it works this way. Thanks!

**Comment by jgm** [comment]
No semantic difference.

**Comment by ioquatix** [comment]
Do you think we should capture this or normalise it, and what would be more standard? 1 or 2 spaces? Because I always used one space for lists, so the normalisation process is causing a lot of edit noise when lists are involved.

**Comment by ioquatix** [comment]
Oh, I took a look at the code since I had it open:

```c
      // we ensure a width of at least 4 so
      // we get nice transition from single digits
      // to double
      snprintf(listmarker, LISTMARKER_SIZE, "%d%s%s", list_number,
               list_delim == CMARK_PAREN_DELIM ? ")" : ".",
               list_number < 10 ? "  " : " ");
```

It looks like double spacing is used to keep lists with 10+ items aligned at the same starting character.

**Comment by ioquatix** [comment]
I'm going to close the issue because at least the way it works is logical. However, maybe one small optimisation that could be made, is if there are < 10 items, the list is not indented with 2 spaces.
