### ISSUE TITLE
Merge hotdoc changes into main line

### ISSUE THREAD

**Issue by kloczek** [commonmark/cmark#351]
https://github.com/MathieuDuponchelle/cmark fork has dsome adaptations used by hotdoc.

Is it aby chance to merge tose changes into cmark?

**Comment by jgm** [comment]
This is too unspecific.  If there is a certain change you're interested in, please identify it.
Any PR should be for one atomic change.

**Comment by kloczek** [comment]
As you can see in hotdoc ticlket I've asked to send necessary changes in smaller chunks.
Good to see that you are opened on review those changes.

Thx :)
