### ISSUE TITLE
Tab after # character in ATX heading creates a header

### ISSUE THREAD

**Issue by gpanders** [commonmark/cmark#352]
I'm not sure if this is a bug in the `cmark` implementation or an oversight in the spec.

The specification states:

> The opening sequence of # characters must be followed by a space or by the end of line.

Where space is defined:

> A space is `U+0020`.

However, the following Markdown snippet (note the hard tab character after the `#`):
```markdown
#	hello
```

compiles to

```html
<h1>hello</h1>
```

My hunch is that this is expected behavior and the spec itself needs to be updated to indicate that the `#` character needs to be followed by whitespace (not just `U+0020`), but I wanted to make sure.

**Comment by jgm** [comment]
The current version in `master` already reads:
"The opening sequence of `#` characters must be followed by spaces or tabs, or
by the end of line."

So this is fixed, just not yet in a release.
