### ISSUE TITLE
Inconsistent results when nesting > * >

### ISSUE THREAD

**Issue by crestonbunch** [commonmark/cmark#353]
This is an issue where a `&gt;` is rendered where it should not be.

Here is a simple test case. The issue is present in the last two lines:

test.md:

```markdown
> * > A
>   > B

> * > A
>     B

> * > A
      B

> * > A
    > B
```

```
$ cmark test.md
<blockquote>
<ul>
<li>
<blockquote>
<p>A
B</p>
</blockquote>
</li>
</ul>
</blockquote>
<blockquote>
<ul>
<li>
<blockquote>
<p>A
B</p>
</blockquote>
</li>
</ul>
</blockquote>
<blockquote>
<ul>
<li>
<blockquote>
<p>A
&gt; B</p>
</blockquote>
</li>
</ul>
</blockquote>
```

The issue is in the last blockquote:
```
<blockquote>
<p>A
&gt; B</p>
</blockquote>
</li>
```

I would expect it to render the same as the others without the `&gt;`.

Let me know if this is an actual issue or a misunderstanding. Thanks!

```
$ cmark --version
cmark 0.29.0 - CommonMark converter
(C) 2014-2016 John MacFarlane
```

**Comment by jgm** [comment]
Interesting case.

The spec says:

> Laziness. If a string of lines Ls constitute a block quote with contents Bs, then the result of deleting the initial block quote marker from one or more lines in which the next non-whitespace character after the block quote marker is paragraph continuation text is a block quote with Bs as its content. Paragraph continuation text is text that will be parsed as part of the content of a paragraph, but does not occur at the beginning of the paragraph.

Does that apply here?  You might be assuming that
```
> * > A
    > B
```
is a lazy reduction of
```
> * > A
>   > B
```
But actually it isn't according to the spec, because of this clause:

> the result of deleting the initial block quote marker from one or more lines **in which the next non-whitespace character after the block quote marker is paragraph continuation text** is a block quote with Bs as its content

The next non-whitespace character after the deleted `>` at the beginning of the line is `>`, and that is not paragraph continuation text but rather a marker for the beginning of a block quote.

**Comment by crestonbunch** [comment]
Thanks for the thorough response! It sounds like this is according to the spec, so I will close this issue.

FWIW it seems like some non-cmark renderers do it differently:

cmark (correct)
![image](https://user-images.githubusercontent.com/5474116/88605743-d64fd400-d048-11ea-84d0-03cf2f1d1ec0.png)

https://github.com/markdown-it/markdown-it which claims to follow the CommonMark spec :shrug:
![image](https://user-images.githubusercontent.com/5474116/88605607-62adc700-d048-11ea-9a3d-dd0d8aa1c193.png)

https://github.com/benweet/stackedit/
![image](https://user-images.githubusercontent.com/5474116/88605628-778a5a80-d048-11ea-9e29-a1a61e171acc.png)
