### ISSUE TITLE
please issue a formal release

### ISSUE THREAD

**Issue by jonassmedegaard** [commonmark/cmark#382]
Latest release of this project now has 2 year anniversary, and (from a quick glance) quite a few bugs has been fixed since then.

Please consider issuing a release of this new exciting set of improvements.  What might speak against that? Any known regressions among the currently open issues?

**Comment by jgm** [comment]
Yes, this is long overdue.  The main issue is that the changes include updates to spec.txt, so the release needs to be coordinated with releases of commonmark-spec and commonmark.js.  At the moment I'm overloaded with other tasks, but I hope to do it before the end of May.

**Comment by jgm** [comment]
In other words: this can't be a 0.29.1 release, because of the spec changes; it has to be 0.30.0, but this requires an 0.30.0 release of the spec too, since currently the version numbers are tied together.

**Comment by LorenDB** [comment]
I would really appreciate a release for the sake of [nheko](https://github.com/Nheko-Reborn/nheko), as we would like to fix [this](https://github.com/Nheko-Reborn/nheko/issues/182) bug that requires a new cmark release.

**Comment by jgm** [comment]
It's on my list for this summer.  Hopefully by the end of the month.

**Comment by jgm** [comment]
Release 0.30.0 is out.
