### ISSUE TITLE
Line spacing of items in an unordered list is different if an item contains a fenced code block with an blank line before

### ISSUE THREAD

**Issue by regseb** [commonmark/cmark#440]
The line spacing of items in an unordered list is different if an item contains a fenced code block with an blank line before ([live demo](https://spec.commonmark.org/dingus/?text=%23%23%20%E2%9C%94%EF%B8%8F%20Unordered%20list%20without%20fenced%20code%20block%0A%0A-%20foo%0A-%20bar%0A-%20baz%0A%0A%23%23%20%E2%9C%94%EF%B8%8F%20Unordered%20list%20with%20fenced%20code%20block%20without%20blank%20line%0A%0A-%20foo%0A-%20bar%0A%20%20%60%60%60%0A%20%20baz%0A%20%20%60%60%60%0A%0A%23%23%20%E2%9D%8C%20Unordered%20list%20with%20fenced%20code%20block%20with%20blank%20line%0A%0A-%20foo%0A-%20bar%0A%0A%20%20%60%60%60%0A%20%20baz%0A%20%20%60%60%60)).

I want to add a blank line to respect the [`blanks-around-fences`](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md031) rule of markdownlint:

> _Aside from aesthetic reasons, some parsers, including kramdown, will not parse fenced code blocks that don't have blank lines before and after them._

### Markdown

<pre>
- foo
- bar
- baz
</pre>

### Rendering

- foo
- bar
- baz

### Markdown

<pre>
- foo
- bar
  ```
  baz
  ```
</pre>

### Rendering

- foo
- bar
  ```
  baz
  ```

### Markdown

<pre>
- foo
- bar

  ```
  baz
  ```
</pre>

### Rendering

- foo
- bar

  ```
  baz
  ```

**Comment by jgm** [comment]
This is in accordance with what the spec says about tight vs loose lists, isn't it?

**Comment by jgm** [comment]
So, not a bug.
See https://spec.commonmark.org/0.30/#loose
