### ISSUE TITLE
Make `CMARK_OPT_UNSAFE` settable during runtime

### ISSUE THREAD

**Issue by hinell** [commonmark/cmark#477]
Hi. I'm linking against library and would like to be able to set `CMARK_OPT_UNSAFE` via method options,

Currently it's respected only during compile time and in cli binary.

Thanks!

**Comment by nwellnhof** [comment]
> Currently it's respected only during compile time and in cli binary, which.

This isn't true. CMARK_OPT_UNSAFE can be passed to several API functions at runtime.

**Comment by hinell** [comment]
@nwellnhof No doubt about that but is there any way oen can pass it to the `... cmark_markdown_to_html(...)` call? Thanks.

**Comment by nwellnhof** [comment]
Here's the declaration of `cmark_markdown_to_html`:

```c
char *cmark_markdown_to_html(const char *text, size_t len, int options);
```

Just pass `CMARK_OPT_UNSAFE`, maybe ORed with other flags, as `options` argument.

**Comment by hinell** [comment]
@nwellnhof Sorry, didn't notice the definitions: 

https://github.com/commonmark/cmark/blob/7195c6735f29be947ddc41f86c9ddfc8621d33b9/src/cmark.h#L545-L571

Thanks!

**Comment by hinell** [comment]
@nwellnhof Sorry, didn't notice the definitions. They are buried below, which is kinda surprising: 

https://github.com/commonmark/cmark/blob/7195c6735f29be947ddc41f86c9ddfc8621d33b9/src/cmark.h#L545-L571

Thanks!
