### ISSUE TITLE
Part of the code is under GPL2

### ISSUE THREAD

**Issue by bkmgit** [commonmark/cmark#480]
Pointed out in code review is that [buffer.h](https://github.com/commonmark/cmark/blob/master/src/buffer.h) and [buffer.c](https://github.com/commonmark/cmark/blob/master/src/buffer.c) seem to be derived from [Houdini buffer.h](https://github.com/vmg/houdini/blob/master/buffer.h) and [Houdini buffer.c](https://github.com/vmg/houdini/blob/master/buffer.c) which are available under GPL2 with a linking exception and originally came from libgit2

**Comment by jgm** [comment]
buffer was added by @vmg who at the time was working for GitHub, where this code was developed.
@vmg certified in https://github.com/commonmark/commonmark-spec/pull/269 that the license was correct.

**Comment by jgm** [comment]
By the way @vmg is also one of the libgit2 contributors.  Hopefully @vmg can comment here to clarify things.

**Comment by vmg** [comment]
The PR in https://github.com/commonmark/commonmark-spec/pull/269 is the authoritative source for licensing information.

> @vmg certifies by merging this PR that the license and copyright information are accurate.

I approved that PR and re-licensed the code under the same permissive license as the rest of `cmark`. There is no GPLv2 code in `cmark` because that would make the library useless.

**Comment by bkmgit** [comment]
Thanks. A related issue is the copyright notices on utf8.h and utf8.c

https://github.com/github/cmark-gfm/issues/348

**Comment by bkmgit** [comment]
Associated pull request https://github.com/commonmark/cmark/pull/483
