### ISSUE TITLE
How to support a link with space?

### ISSUE THREAD

**Issue by tienll** [commonmark/cmark#485]
For example,

`[Title](Link To The Resource)`

The parsing is failed due to the space, is that possible to somehow make it work?

**Comment by jgm** [comment]
URI-encode the spaces as `%20`.

**Comment by tienll** [comment]
> URI-encode the spaces as `%20`.

Thank you @jgm. Yes encoding should be working, however parsing with space can improve the readability I think. 
Or where is the best place that I shall begin with if I want to change the code for this?

**Comment by jgm** [comment]
The code is fine, it conforms to the spec:

https://spec.commonmark.org/0.30/#link-destination

As noted there, another option would be to include the whole thing in `<..>`, then you can use spaces (but not newlines).

**Comment by tienll** [comment]
> <..>

Thanks, that's a great solution!
