### ISSUE TITLE
[iOS] Does this SDK need a Privacy Manifest?

### ISSUE THREAD

**Issue by tinder-jaylinphipps** [commonmark/cmark#539]
With the latest changes to apples privacy manifest requirements. Does using this SDK require the need for a privacy manifest?

Reference:
https://developer.apple.com/support/third-party-SDK-requirements/#:~:text=Starting%20in%20spring%202024%2C%20you,as%20part%20of%20the%20update.

**Comment by jgm** [comment]
What does this have to do with cmark?

**Comment by tinder-jaylinphipps** [comment]
Apple forks the common mark repo, so just validating. But seems to your response it isn't needed.
